# Generated by Django 4.2.5 on 2023-09-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_history_alter_personaldata_proper_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='History',
            new_name='HistoryData',
        ),
    ]
