# Generated by Django 4.2.5 on 2023-09-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_history_historydata'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pic_url',
            field=models.CharField(default='http', max_length=100),
            preserve_default=False,
        ),
    ]
