# Generated by Django 4.2.5 on 2023-09-13 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0006_rename_history_historydata"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="img_url",
            field=models.CharField(default="a", max_length=300),
            preserve_default=False,
        ),
    ]
