# Generated by Django 4.2.5 on 2023-09-13 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_shop_img_url'),
        ('App', '0007_shop_pic_url'),
    ]

    operations = [
    ]
