# Generated by Django 4.2.5 on 2023-09-13 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_merge_0007_shop_img_url_0007_shop_pic_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='pic_url',
        ),
        migrations.AlterField(
            model_name='historydata',
            name='shop_id',
            field=models.IntegerField(),
        ),
    ]
