# Generated by Django 4.2.5 on 2023-09-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0009_personaldata_birthday_personaldata_gender_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historydata",
            name="shop_name",
            field=models.CharField(default="test_shopname", max_length=100),
            preserve_default=False,
        ),
    ]
