# Generated by Django 4.2.5 on 2023-09-14 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_remove_shop_pic_url_alter_historydata_shop_id'),
        ('App', '0010_historydata_shop_name'),
    ]

    operations = [
    ]
